
{{- if .Values.backup_v2.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  annotations:
{{- if .Values.backup_v2.oauth.sap_id }}
    ingress.kubernetes.io/auth-url: https://auth-internal.{{ .Values.global.region }}.cloud.sap/oauth2/auth
    ingress.kubernetes.io/auth-signin: https://auth-internal.{{ .Values.global.region }}.cloud.sap/oauth2/start
    ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-Email, X-Auth-Request-User, X-Forwarded-Access-Token"
{{- end }}
    kubernetes.io/tls-acme: "true"
  name:  {{ include "fullName" . }}-backup

spec:
  rules:
    - host:  {{ .Values.name }}.mariabackup.{{ .Values.global.region }}.cloud.sap
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "fullName" . }}-backup
                port:
                  number: 8081
  tls:
    - hosts:
      -  {{ .Values.name }}.mariabackup.{{ .Values.global.region }}.cloud.sap
      secretName: tls-{{ .Values.name }}-mariabackup-{{ .Values.global.region }}-cloud-sap
{{- end }}
