region: __DEFINED_AS_ARG__

# to be set on the cli to specify the actual services, domains, instances to deploy
# service_1, domain_1, instance_1, instance_2 will deploy all deployments in s1 d1
deploy: []

registry:

apod: true
#only required if apod == true
px_availability_zones: []

# only required if apod != true
scheduling_labels:
  domain_1: []
  domain_2: []

bird_config_path:

bird_exporter_image:
bird_image:
lg_image:


looking_glass:
  lg:
    proxy_port:
  lgadmin:
    proxy_port:

config:
  service_1:
    domain_1:
      multus_vlan:
      instance_1:
        multus_ip:
      instance_2:
        multus_ip:
    domain_2:
      multus_vlan:
      instance_1:
        multus_ip:
      instance_2:
        multus_ip:


  service_2:
    domain_1:
      multus_vlan:
      instance_1:
        multus_ip:
      instance_2:
        multus_ip:
    domain_2:
      multus_vlan:
      instance_1:
        multus_ip:
      instance_2:
        multus_ip:


  service_3:
    domain_1:
      multus_vlan:
      instance_1:
        multus_ip:
      instance_2:
        multus_ip:
    domain_2:
      multus_vlan:
      instance_1:
        multus_ip:
      instance_2:
        multus_ip: