global:
  domain: cloud.sap
  clusterType: controlplane
  alerts:
    enabled: true
    prometheus: vmware

  aggregations:
    enabled: true
    prometheus: vmware

prometheus-server:
  name: vmware
  retentionTime: 8h

  additionalScrapeConfigs: {}

  scrapeInterval: "60s"

  alertmanagers:
    hosts:
      - alertmanager-internal.scaleout.eu-de-1.cloud.sap
      - alertmanager-internal.scaleout.eu-nl-1.cloud.sap

  ingress:
    enabled: true
    hosts:
      - prometheus-vmware
    authentication:
      sso:
        enabled: true
        authTLSSecret: kube-system/ingress-cacrt
        authTLSVerifyDepth: 3
        authTLSVerifyClient: on

  internalIngress:
    enabled: true
    hosts:
      - prometheus-vmware-internal
    authentication:
      sso:
        enabled: true
        authTLSSecret: kube-system/ingress-cacrt
        authTLSVerifyDepth: 3
        authTLSVerifyClient: on

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 100Gi

  rbac:
    create: true

  serviceAccount:
    create: true

  logLevel: info

  resources:
    requests:
      cpu: 500m
      memory: 4Gi

  securityContext:
    fsGroup: 0
    runAsUser: 0

  serviceDiscoveries:
    endpoints:
      enabled: true
      limitToPrometheusTargets: true

    pods:
      enabled: false



  alerts:
    tier: monitor

kube-state-metrics-exporter:
  prometheusName: vmware

vropsExporter:
  enabled: true
  prometheusName: vmware
  scrapeInterval: 180s
  scrapeTimeout: 175s
