{{ if .Values.global_deployment }}
kind: Deployment
apiVersion: apps/v1

metadata:
  name: bastion-global
spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: bastion-global
  template:
    metadata:
      labels:
        name: bastion-global
      annotations:
        checksum/configmap: {{ include "bastion/templates/etc-configmap.yaml" . | sha256sum }}
        checksum/secret: {{ include "bastion/templates/secret.yaml" . | sha256sum }}
    spec:
      volumes:
        - name: bastion-etc
          configMap:
            name: bastion-etc
        - name: bastion-secret
          secret:
            secretName: bastion-secret
      containers:
        - name: global
          image: {{required ".Values.global.registry is missing" .Values.global.registry }}/{{required "Values.image is missing" .Values.image}}:{{required "Values.image_tag is missing" .Values.image_tag}}
          imagePullPolicy: Always
          args: [ bastion_global, "--config-file", "/etc/config/bastion-global.conf","--config-file", "/etc/config/logging.conf"]
          env: {{ include "bastion_environment" $ | indent 12 }}
          volumeMounts:
            - mountPath: /etc/config
              name: bastion-etc
            - mountPath: /etc/secret
              name: bastion-secret
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
{{ end }}