apiVersion: v1
kind: ConfigMap
metadata:
  name: bastion-etc
  labels:
    system: openstack
    type: configuration
    component: barbican
data:
  bastion.conf: |
{{ include (print .Template.BasePath "/etc/_bastion.conf.tpl") . | indent 4 }}
  bastion-global.conf: |
{{ include (print .Template.BasePath "/etc/_bastion-global.conf.tpl") . | indent 4 }}
  logging.conf: |
{{ include (print .Template.BasePath "/etc/_logging.conf.tpl") . | indent 4 }}

