kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: bastion
  annotations:
    kubernetes.io/tls-acme: "true"
    disco: "true"

spec:
  tls:
    - secretName: tls-bastion-api
      hosts: [ bastion.{{ .Values.global.region }}.{{ .Values.global.tld }} ]
  rules:
    - host: bastion.{{ .Values.global.region }}.{{ .Values.global.tld }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bastion-region
                port:
                  number: 8080
