apiVersion: v1
kind: Secret
metadata:
  name: bastion-secret
data:
  ldap_user: {{ .Values.ldap.username | b64enc}}
  ldap_password: {{ .Values.ldap.password | b64enc}}
  keystone_db_username: {{ .Values.db.username | b64enc}}
  keystone_db_password: {{ .Values.db.password | b64enc}}
  prom_cert.pem: {{ .Values.prometheus.authentication.sso_cert | b64enc}}
  prom_cert.key: {{ .Values.prometheus.authentication.sso_key | b64enc}}

