kind: Service
apiVersion: v1

metadata:
  name: bastion-region
  annotations:
#    prometheus.io/scrape: "true"
#    prometheus.io/port: "8080"
#    prometheus.io/targets: "infra-collector"
spec:
  selector:
    name: bastion-region
  ports:
    - port: 8080
