{{- if .Values.manila_nanny.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-netapp-filers
  labels:
    system: openstack
    service: manila-nanny
data:
  netapp-filers.conf: |
    filers:
      {{- range .Values.global.netapp.filers }}
      - {{ .host }}
      {{- end}}
{{- end }}
