{{- if .Values.manila_nanny.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: manila-nanny-secret
data:
  {{- with (first .Values.global.netapp.filers)}}
  manila_netapp_api_username: {{ .username | b64enc }}
  manila_netapp_api_password: {{ .password | b64enc }}
  {{- end }}
{{- end }}
