apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-bin
  labels:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: keystone
    type: config
data:
  bootstrap: |
{{ include (print .Template.BasePath "/bin/_bootstrap.tpl") . | indent 4 }}
  cron: |
{{ include (print .Template.BasePath "/bin/_cron.tpl") . | indent 4 }}
  db-sync: |
{{ include (print .Template.BasePath "/bin/_db-sync.tpl") . | indent 4 }}
  keystone-api.sh: |
{{ include (print .Template.BasePath "/bin/_keystone_api.sh.tpl") . | indent 4 }}
{{- if .Values.tempest.enabled }}
  keystone-tempest.sh: |
{{ include (print .Template.BasePath "/bin/_keystone_tempest.sh.tpl") . | indent 4 }}
{{- end}}
  region-check.py: |
{{ .Files.Get "files/region-check.py" | indent 4 }}
