{{- range $service, $service_config := .Values.config -}}
{{ if and (hasPrefix "service_" $service) (has $service $.Values.deploy) }}
{{- $service_number := trimPrefix "service_" $service | int -}}

{{- range $domain, $domain_config := $service_config -}}
{{ if and (hasPrefix "domain_" $domain) (has $domain $.Values.deploy) }}
{{- $domain_number := trimPrefix "domain_" $domain | int -}}

{{- range $instance, $instance_config := $domain_config -}}
{{ if and (hasPrefix "instance_" $instance) (has $instance $.Values.deploy) }}
{{- $instance_number := trimPrefix "instance_" $instance | int -}}
{{- $deployment_name := printf "%s-pxrs-%d-s%d-%d" $.Values.region $domain_number $service_number $instance_number -}}

---
{{- tuple $deployment_name $.Values.apod $.Values.scheduling_labels $.Values.px_availability_zones
          $domain_config.multus_vlan $service_number $service $domain_number $domain $instance_number $instance | include "deployment_header" }}
      initContainers:
      - name: {{ $deployment_name }}-init
        image: busybox
        command: ["sh", "-c", "ip link set vlan{{ $domain_config.multus_vlan }} promisc on"]
        securityContext:
          privileged: true
      containers:
      - name: {{ $deployment_name }}
        image: keppel.{{ $.Values.registry }}.cloud.sap/{{ $.Values.bird_image }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        imagePullPolicy: Always
        volumeMounts:
        - name: vol-{{ $deployment_name }}
          mountPath: /etc/bird
        - name: bird-socket
          mountPath: /var/run/bird
        livenessProbe:
          exec:
            command: ["bird-command", "--liveness"]
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: {{ $deployment_name }}-exporter
        image: keppel.{{ $.Values.region }}.cloud.sap/{{$.Values.bird_exporter_image}}
        args: ["-format.new=true", "-bird.v2", "-bird.socket=/var/run/bird/bird.ctl", "-proto.ospf=false", "-proto.direct=false"]
        volumeMounts:
        - name: bird-socket
          mountPath: /var/run/bird
          readOnly: true
        ports:
        - containerPort: 9324
          name: metrics
      - name: {{ $deployment_name }}-lgproxy
        image: keppel.{{ $.Values.region }}.cloud.sap/{{ $.Values.lg_image }}
        command: ["python3"]
        args: ["lgproxy.py"]
        volumeMounts:
        - name: bird-socket
          mountPath: /var/run/bird
          readOnly: true
        ports:
        - containerPort: 5000
          name: lgproxy
      - name: {{ $deployment_name }}-lgadminproxy
        image: keppel.{{ $.Values.region }}.cloud.sap/{{ $.Values.lg_image }}
        command: ["python3"]
        args: ["lgproxy.py", "priv"]
        volumeMounts:
        - name: bird-socket
          mountPath: /var/run/bird
          readOnly: true
        ports:
        - containerPort: 5005
          name: lgadminproxy
      volumes:
        - name: vol-{{ $deployment_name }}
          configMap:
            name: cfg-{{ $.Values.region }}-pxrs-{{ $domain_number }}-s{{ $service_number }}
        - name: bird-socket
          emptyDir: {}

{{ end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
