{{- range $service, $service_config := .Values.config -}}
{{ if and (hasPrefix "service_" $service) (has $service $.Values.deploy) }}
{{- $service_number := trimPrefix "service_" $service | int -}}

{{- range $domain, $domain_config := $service_config -}}
{{ if and (hasPrefix "domain_" $domain) (has $domain $.Values.deploy) }}
{{- $domain_number := trimPrefix "domain_" $domain | int -}}

{{- range $instance, $instance_config := $domain_config -}}
{{ if and (hasPrefix "instance_" $instance) (has $instance $.Values.deploy) }}
{{- $instance_number := trimPrefix "instance_" $instance | int -}}
{{- $deployment_name := printf "%s-pxrs-%d-s%d-%d-pxmon" $.Values.region $domain_number $service_number $instance_number -}}
{{- if hasKey $instance_config "pxmon_ip" -}}

---
{{- tuple $deployment_name $.Values.apod $.Values.scheduling_labels $.Values.px_availability_zones
          $domain_config.multus_vlan $service_number $domain_number $instance_number | include "deployment_header" }}
      initContainers:
      - name: {{ $deployment_name }}-init
        image: busybox
        command: ["sh", "-c", "ip link set vlan{{ $domain_config.multus_vlan }} promisc on"]
        securityContext:
          privileged: true
      containers:
      - name: {{ $deployment_name }}
        image: keppel.{{ $.Values.region }}.cloud.sap/{{ $.Values.bird_image }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        imagePullPolicy: Always
        volumeMounts:
        - name: vol-{{ $deployment_name }}
          mountPath: /etc/bird
        - name: bird-socket
          mountPath: /var/run/bird
        livenessProbe:
          exec:
            command:
            - python3
            - bird-command.py
            - --liveness
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: {{ $deployment_name }}-prober
        image: cloudprober/cloudprober:v0.10.6
        volumeMounts:
          - name: vol-{{ $deployment_name }}-prober
            mountPath: /cfg
        command: ["/cloudprober"]
        args: ["--config_file", "/cfg/{{ $deployment_name }}-prober.cfg", "--logtostderr"]
        ports:
        - containerPort: 9313
          name: metrics
      volumes:
        - name: vol-{{ $deployment_name }}
          configMap:
            name: cfg-{{ $deployment_name }}
        - name: vol-{{ $deployment_name }}-prober
          configMap:
            name: cfg-{{ $deployment_name }}-prober
        - name: bird-socket
          emptyDir: {}
{{ end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
