{{- if .Values.enabled }}
{{- $values := .Values -}}

{{- range $i, $prober := .Values.probers -}}
{{ if ne $i 0 }}---{{ end }}

apiVersion: v1
kind: Service

metadata:
  name: cloudprober-{{$prober.dc}}
  labels:
    app: cloudprober
  annotations:
    prometheus.io/scrape: {{ required ".Values.metrics.scrape variable missing" $values.metrics.scrape | quote }}
    prometheus.io/port: {{ required ".Values.metrics.port variable missing" $values.metrics.port | quote }}
    prometheus.io/targets: {{ required ".Values.metrics.prometheus variable missing" $values.metrics.prometheus | quote }}
spec:
  selector:
    name: cloudprober-{{$prober.dc}}
  externalIPs:
    - {{$prober.ip}}
  ports:
    - name: metrics
      port: 9313
      targetPort: 9313
    - name: web
      port: 1080
      targetPort: 8080

---
{{ end -}}
{{ end -}}
