image_bind: bind
image_bind_exporter: bind_exporter
image_bind_tag: "20211102151001"
image_bind_exporter_tag: "20201112130820"
image_pullPolicy: IfNotPresent
externalIP: DEFINED-REGION-CHART
allow_notify: DEFINED-REGION-CHART
master_server: DEFINED-REGION-CHART
rndc_allow: DEFINED-REGION-CHART 
rndc_key: DEFINED-REGION-CHART
tsig_key: DEFINED-REGION-CHART
failure_domain_zone: a
pvc_size: "1Gi"
pvc_zone_selector: false
name: bind

alerts:
  # Name of the Prometheus to which the alerts should be assigned to.
  prometheus: openstack
