{{- if and .Values.backup_v2.alerts.enabled .Values.backup_v2.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: metis-replication-alerts
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: metisdb
    helm.sh/chart: {{ include "metis.chart" $ }}
    app.kubernetes.io/instance: metisdb-{{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    prometheus: {{ required ".Values.backup_v2.alerts.prometheus missing"  .Values.backup_v2.alerts.prometheus }}

spec:
  groups:
{{ include (print .Template.BasePath "/alerts/_replication.alerts.tpl") . | indent 2 }}

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: metis-kubernetes-alerts
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: metisdb
    helm.sh/chart: {{ include "metis.chart" $ }}
    app.kubernetes.io/instance: metisdb-{{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    prometheus: kubernetes

spec:
  groups:
{{ include (print .Template.BasePath "/alerts/_database.alerts.tpl") . | indent 2 }}
{{- end }}
