{{- if .Values.updatesProxy.storageUrl }}
{{- range $ing := .Values.updatesProxy.ingress }}
{{- $name := index $ing.hosts 0 }}
{{- if $ing.tlsCertificate }}
---
kind: Secret
apiVersion: v1

metadata:
  name: ingress-{{ $name | replace "." "-" }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
data:
  tls.crt: {{ $ing.tlsCertificate | b64enc }}
  tls.key: {{ $ing.tlsKey | b64enc }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ $name | replace "." "-" }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
  {{- if $ing.cert_manager}}
  annotations:
    kubernetes.io/tls-acme: "true"
  {{- end }}
spec:
  tls:
     - secretName: ingress-{{ $name | replace "." "-" }}
       hosts:
{{ toYaml $ing.hosts | indent 10}}
  rules:
{{- range $host := $ing.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: arc-updates-proxy
            port:
              number: 80
{{- end }}
{{- end }}
{{- end }}
