{{ range $lg, $lg_config := .Values.looking_glass -}}
---
kind: ConfigMap
apiVersion: v1
metadata:
    name: {{ $.Values.region }}-pxrs-{{ $lg }}
data:
    "{{ $.Values.region }}-pxrs-{{ $lg }}.cfg": |
{{ tuple $.Values.region $lg_config | include "lg_conf" | indent 8 }}

{{ end }}