{{- $config_path := printf "%s%s.json" $.Values.bird_config_path "lg_px_communities_v2" -}}
---
kind: ConfigMap
apiVersion: v1
metadata:
    name: cfg-{{ $.Values.global.region }}-pxrs-lg-communities
data:
    "{{ $.Values.global.region }}-pxrs-lg-communities.cfg": |
{{ $.Files.Get $config_path | indent 8}}
